<a href="https://colab.research.google.com/github/fcoelopes/Ada/blob/main/Intro_Ada.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
lista = [1, 2, 3, 4, 5, 6]
array = np.array(lista)
print(array)

[1 2 3 4 5 6]


In [4]:
print(type(list))
print(type(array))

<class 'type'>
<class 'numpy.ndarray'>


In [5]:
arr_zeros = np.zeros(10)
print(arr_zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
array[0] = 9
print(array)

[9 2 3 4 5 6]


In [7]:
#Matrizes
matriz_zeros = np.zeros((5, 3))
print(matriz_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [9]:
lista_de_notas = [9.8, 5.6, 7.8, 9.1, 6.5]
notas = np.array(lista_de_notas)
print(notas)

[9.8 5.6 7.8 9.1 6.5]


In [11]:
print("Maior nota: ", np.max(notas))
print("Menor nota: ", np.min(notas))
print("Desvio padrão: ", np.std(notas))
print("Média das notas: ", np.mean(notas))
print("Posição da menor nota: ", np.argmin(notas))
print("Posição da maior nota: ", np.argmax(notas))

Maior nota:  9.8
Menor nota:  5.6
Desvio padrão:  1.5628179676469045
Média das notas:  7.76
Posição da menor nota:  1
Posição da maior nota:  0


# Mascaras booleanas

In [16]:
is_covid_positive = np.array(['Yes', 'No', 'No', 'Yes', 'Yes', 'No'])
print(is_covid_positive)

['Yes' 'No' 'No' 'Yes' 'Yes' 'No']


In [17]:
mask = (is_covid_positive == 'Yes')
print(mask)

[ True False False  True  True False]


In [18]:
print(is_covid_positive[0])

Yes


In [19]:
print(is_covid_positive[mask])

['Yes' 'Yes' 'Yes']


In [20]:
is_covid_positive[mask] = 'C19'
print(is_covid_positive)

['C19' 'No' 'No' 'C19' 'C19' 'No']


In [21]:
notas2 = np.array([4.9, 6.5, 3.2, 6.7])

In [24]:
mask_notas = (notas2 >=5)
print(mask_notas)

[False  True False  True]
